pathname: db/models/sql/subqueries.py

module:
  new_imports:
    - "from django_async_backend.db.models.sql.query import Query"

  import_aliases:
    - name: Query
      remove: true

  classes:
    UpdateQuery:
      methods:
        update_batch:
          to_async: true
          calls:
            - func:
                attr: execute_sql
              to_await: true
    DeleteQuery:
      remove: true

    AggregateQuery:
      remove: true
