pathname: db/models/fields/related_descriptors.py

module:
  new_imports:
    - "from django.db.models.fields import related_descriptors as django_related_descriptors"
    - "from django_async_backend.db import async_connections"
    - "from django_async_backend.db.models.query import QuerySet"
    - "from django_async_backend.db.transaction import async_atomic"

  import_aliases:
    - name: QuerySet
      remove: true
    - name: sync_to_async
      remove: true
    - name: connections
      remove: true
    - name: transaction
      remove: true

  functions:
    _filter_prefetch_queryset:
      remove: true

    create_reverse_many_to_one_manager:
      remove: true

  classes:
    ForeignKeyDeferredAttribute:
      remove: true

    ForwardManyToOneDescriptor:
      remove: true

    ForwardOneToOneDescriptor:
      remove: true

    ReverseOneToOneDescriptor:
      remove: true

    ReverseManyToOneDescriptor:
      remove: true

    ManyToManyDescriptor:
      remove: true

    ManyRelatedManager:
      assigns:
        - target:
            value: add
            rename:
              value: aadd

        - target:
            value: remove
            rename:
              value: aremove

        - target:
            value: clear
            rename:
              value: aclear

        - target:
            value: set
            rename:
              value: aset

        - target:
            value: create
            rename:
              value: acreate

        - target:
            value: get_or_create
            rename:
              value: aget_or_create

        - target:
            value: update_or_create
            rename:
              value: aupdate_or_create

        - target:
            value: aadd
          remove: true

        - target:
            value: aremove
          remove: true

        - target:
            value: aclear
          remove: true

        - target:
            value: aset
          remove: true

        - target:
            value: acreate
          remove: true

        - target:
            value: aget_or_create
          remove: true

        - target:
            value: aupdate_or_create
          remove: true

      methods:
        __call__:
          calls:
            - func:
                name: create_forward_many_to_many_manager
              replace_raw: |
                django_related_descriptors.create_forward_many_to_many_manager(
                    manager.__class__, rel, reverse
                )

        _build_remove_filters:
          add_raw_top:
            - |
              if isinstance(removed_vals, QuerySet):
                  removed_vals = removed_vals.values(
                      self.target_field.target_field.attname
                  )

        get_prefetch_querysets:
          remove: true

        constrained_target:
          remove: true

        exists:
          remove: true

        count:
          remove: true

        aadd:
          remove: true

        aremove:
          remove: true

        aclear:
          remove: true

        aset:
          remove: true

        acreate:
          remove: true

        aget_or_create:
          remove: true

        aupdate_or_create:
          remove: true

        _add_base:
          to_async: true
          context_managers:
            - to_async: true
          calls:
            - func:
                value: transaction
                attr: atomic
                rename:
                  name: async_atomic
            - func:
                attr: _add_items
              to_await: true

        add:
          to_async: true
          rename: aadd
          calls:
            - func:
                attr: _add_base
              to_await: true

        _remove_base:
          to_async: true
          calls:
            - func:
                attr: _remove_items
              to_await: true

        remove:
          to_async: true
          rename: aremove
          calls:
            - func:
                attr: _remove_base
              to_await: true

        _clear_base:
          to_async: true
          context_managers:
            - to_async: true
          attrs:
            - name: _default_manager
              rename:
                name: _async_base_manager
          calls:
            - func:
                value: transaction
                attr: atomic
                rename:
                  name: async_atomic
            - func:
                parent_attr: m2m_changed
                attr: send
                rename:
                  attr: asend
              to_await: true
            - func:
                attr: delete
                rename:
                  attr: adelete
              to_await: true

        clear:
          to_async: true
          rename: aclear
          calls:
            - func:
                attr: _clear_base
              to_await: true

        set_base:
          to_async: true
          context_managers:
            - to_async: true
          calls:
            - func:
                name: tuple
              args:
                - func:
                    name: objs
              replace_raw: |
                (
                    [obj async for obj in objs]
                    if isinstance(objs, QuerySet)
                    else tuple(objs)
                )
            - func:
                name: set
              args:
                - func:
                    attr: values_list
              replace_raw: |
                {
                    val
                    async for val in self.using(db).values_list(
                        self.target_field.target_field.attname, flat=True
                    )
                }
            - func:
                value: transaction
                attr: atomic
                rename:
                  name: async_atomic
            - func:
                attr: _clear_base
              to_await: true
            - func:
                attr: _add_base
              to_await: true
            - func:
                attr: _remove_base
              to_await: true

        set:
          to_async: true
          rename: aset
          calls:
            - func:
                attr: set_base
              to_await: true

        create:
          to_async: true
          rename: acreate
          calls:
            - func:
                attr: create
                rename:
                  attr: acreate
              to_await: true
            - func:
                attr: add
                rename:
                  attr: aadd
              to_await: true

        get_or_create:
          to_async: true
          rename: aget_or_create
          calls:
            - func:
                attr: get_or_create
                rename:
                  attr: aget_or_create
              to_await: true
            - func:
                attr: add
                rename:
                  attr: aadd
              to_await: true

        update_or_create:
          to_async: true
          rename: aupdate_or_create
          calls:
            - func:
                attr: update_or_create
                rename:
                  attr: aupdate_or_create
              to_await: true
            - func:
                attr: add
                rename:
                  attr: aadd
              to_await: true

        _get_missing_target_ids:
          to_async: true
          attrs:
            - name: _default_manager
              rename:
                name: _async_base_manager
          return_blocks:
            - match_raw: 'target_ids.difference(vals)'
              replace_raw: 'target_ids.difference([val async for val in vals])'

        _get_add_plan:
          attrs:
            - name: connections
              rename:
                name: async_connections

        _add_items:
          to_async: true
          context_managers:
            - to_async: true
          attrs:
            - name: _default_manager
              rename:
                name: _async_base_manager
          calls:
            - func:
                attr: _get_missing_target_ids
              to_await: true
            - func:
                attr: bulk_create
                rename:
                  attr: abulk_create
              to_await: true
            - func:
                value: transaction
                attr: atomic
                rename:
                  name: async_atomic
            - func:
                parent_attr: m2m_changed
                attr: send
                rename:
                  attr: asend
              to_await: true

        _remove_items:
          to_async: true
          context_managers:
            - to_async: true
          attrs:
            - name: _default_manager
              rename:
                name: _async_base_manager
          calls:
            - func:
                value: transaction
                attr: atomic
                rename:
                  name: async_atomic
            - func:
                parent_attr: m2m_changed
                attr: send
                rename:
                  attr: asend
              to_await: true
            - func:
                attr: delete
                rename:
                  attr: adelete
              to_await: true
