# Generated by Django 6.0.2 on 2026-07-13 20:05

from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_dbdefaultpkmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "tag_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TaggedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="tagged", to="test_app.tagmodel"
                    ),
                ),
            ],
            options={
                "db_table": "tagged_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
    ]
