# Generated by Django 6.1.dev20260811223018 on 2026-08-11 17:34

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0004_defaultorderingmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TotalOrderingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(null=True, unique=True)),
                ("headline", models.CharField(max_length=100)),
                ("slug", models.CharField(default="slug", max_length=100)),
                ("pub_date", models.DateField(null=True)),
                ("barcode", models.CharField(default="bar", max_length=30)),
            ],
            options={
                "db_table": "total_ordering_model",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pub_date", "rank"),
                        name="unique_pub_date_rank",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("rank__gt", 0)),
                        fields=("rank",),
                        name="unique_rank_conditional",
                    ),
                    models.UniqueConstraint(
                        fields=("barcode",),
                        name="unique_barcode_empty_condition",
                    ),
                ],
                "unique_together": {("headline", "slug")},
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TotalOrderingChildModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="test_app.totalorderingmodel",
                    ),
                ),
            ],
            options={
                "db_table": "total_ordering_child_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="TotalOrderingRefModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proof",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference",
                        to="test_app.totalorderingmodel",
                    ),
                ),
            ],
            options={
                "db_table": "total_ordering_ref_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
    ]
