# Generated by Django 6.1.dev20260811223018 on 2026-08-11 17:35

from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_app",
            "0005_totalorderingmodel_totalorderingchildmodel_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TotalOrderingCompositePkModel",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "tenant_id",
                        "code",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenant_id", models.IntegerField()),
                ("code", models.IntegerField()),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "total_ordering_composite_pk_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
    ]
