# Generated by Django 6.1.2 on 2026-10-10 10:13

import django.db.models.deletion
from django.db import (
    migrations,
    models,
)

import django_async_backend.db.models.base


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0006_totalorderingcompositepkmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="M2MGroupModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "m2m_group_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="M2MMemberModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "friends",
                    models.ManyToManyField(to="test_app.m2mmembermodel"),
                ),
            ],
            options={
                "db_table": "m2m_member_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="M2MMembershipModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="member", max_length=255)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_app.m2mgroupmodel",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_app.m2mmembermodel",
                    ),
                ),
            ],
            options={
                "db_table": "m2m_membership_model",
            },
            bases=(
                django_async_backend.db.models.base.AsyncModelMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="m2mgroupmodel",
            name="members",
            field=models.ManyToManyField(
                related_name="groups",
                through="test_app.M2MMembershipModel",
                to="test_app.m2mmembermodel",
            ),
        ),
    ]
